# coding: utf-8

"""
    Slurm Rest API RO

    API to access Slurm. Only GET requests are implemented.

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0038_job_resources import V0038JobResources

class TestV0038JobResources(unittest.TestCase):
    """V0038JobResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0038JobResources:
        """Test V0038JobResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0038JobResources`
        """
        model = V0038JobResources()
        if include_optional:
            return V0038JobResources(
                nodes = '',
                allocated_cpus = 56,
                allocated_hosts = 56,
                allocated_nodes = [
                    {"nodename":"nodename","memory":7,"cpus":1,"sockets":{"cores":"{}"}}
                    ]
            )
        else:
            return V0038JobResources(
        )
        """

    def testV0038JobResources(self):
        """Test V0038JobResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
