# coding: utf-8

"""
    Slurm Rest API RO

    API to access Slurm. Only GET requests are implemented.

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0038_errors import V0038Errors

class TestV0038Errors(unittest.TestCase):
    """V0038Errors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0038Errors:
        """Test V0038Errors
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0038Errors`
        """
        model = V0038Errors()
        if include_optional:
            return V0038Errors(
                meta = {"Slurm":{"release":"release","version":{"major":0,"minor":1,"micro":6}},"plugin":{"name":"name","type":"type"}},
                errors = [
                    {"description":"description","source":"source","error":"error","error_number":5}
                    ]
            )
        else:
            return V0038Errors(
        )
        """

    def testV0038Errors(self):
        """Test V0038Errors"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
