# coding: utf-8

"""
    Slurm Rest API RO

    API to access Slurm. Only GET requests are implemented.

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0038_meta_slurm import V0038MetaSlurm

class TestV0038MetaSlurm(unittest.TestCase):
    """V0038MetaSlurm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0038MetaSlurm:
        """Test V0038MetaSlurm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0038MetaSlurm`
        """
        model = V0038MetaSlurm()
        if include_optional:
            return V0038MetaSlurm(
                version = {"major":0,"minor":1,"micro":6},
                release = ''
            )
        else:
            return V0038MetaSlurm(
        )
        """

    def testV0038MetaSlurm(self):
        """Test V0038MetaSlurm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
