# coding: utf-8

"""
    Slurm Rest API RO

    API to access Slurm. Only GET requests are implemented.

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0038_reservations_response import V0038ReservationsResponse

class TestV0038ReservationsResponse(unittest.TestCase):
    """V0038ReservationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0038ReservationsResponse:
        """Test V0038ReservationsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0038ReservationsResponse`
        """
        model = V0038ReservationsResponse()
        if include_optional:
            return V0038ReservationsResponse(
                meta = {"Slurm":{"release":"release","version":{"major":0,"minor":1,"micro":6}},"plugin":{"name":"name","type":"type"}},
                errors = [
                    {"description":"description","source":"source","error":"error","error_number":5}
                    ],
                reservations = [
                    {"core_spec_cnt":6,"end_time":1,"flags":["flags","flags"],"groups":"groups","users":"users","max_start_delay":5,"features":"features","start_time":7,"burst_buffer":"burst_buffer","licenses":"licenses","partition":"partition","watts":9,"name":"name","tres":"tres","accounts":"accounts","node_count":5,"node_list":"node_list","purge_completed":{"time":2},"core_count":0}
                    ]
            )
        else:
            return V0038ReservationsResponse(
        )
        """

    def testV0038ReservationsResponse(self):
        """Test V0038ReservationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
