# coding: utf-8

"""
    Slurm Rest API RO

    API to access Slurm. Only GET requests are implemented.

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0038_partitions_response import V0038PartitionsResponse

class TestV0038PartitionsResponse(unittest.TestCase):
    """V0038PartitionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0038PartitionsResponse:
        """Test V0038PartitionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0038PartitionsResponse`
        """
        model = V0038PartitionsResponse()
        if include_optional:
            return V0038PartitionsResponse(
                meta = {"Slurm":{"release":"release","version":{"major":0,"minor":1,"micro":6}},"plugin":{"name":"name","type":"type"}},
                errors = [
                    {"description":"description","source":"source","error":"error","error_number":5}
                    ],
                partitions = [
                    {"max_time_limit":7,"maximum_cpus_per_node":5,"over_time_limit":3,"denied_accounts":"denied_accounts","flags":["flags","flags"],"maximum_memory_per_node":5,"total_cpus":7,"billing_weights":"billing_weights","default_memory_per_cpu":0,"default_memory_per_node":1,"allowed_qos":"allowed_qos","min_nodes_per_job":9,"qos":"qos","default_time_limit":6,"denied_qos":"denied_qos","priority_job_factor":2,"tres":"tres","allowed_allocation_nodes":"allowed_allocation_nodes","state":"state","preemption_grace_time":1,"allowed_accounts":"allowed_accounts","alternative":"alternative","preemption_mode":["preemption_mode","preemption_mode"],"nodes":"nodes","name":"name","allowed_groups":"allowed_groups","total_nodes":1,"maximum_nodes_per_job":2,"priority_tier":4,"maximum_memory_per_cpu":1}
                    ]
            )
        else:
            return V0038PartitionsResponse(
        )
        """

    def testV0038PartitionsResponse(self):
        """Test V0038PartitionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
