# coding: utf-8

"""
    Slurm Rest API RO

    API to access Slurm. Only GET requests are implemented.

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0038_licenses import V0038Licenses

class TestV0038Licenses(unittest.TestCase):
    """V0038Licenses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0038Licenses:
        """Test V0038Licenses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0038Licenses`
        """
        model = V0038Licenses()
        if include_optional:
            return V0038Licenses(
                errors = [
                    {"description":"description","source":"source","error":"error","error_number":5}
                    ],
                licenses = [
                    {"Used":6,"Total":0,"Remote":true,"LicenseName":"LicenseName","Free":1,"Reserved":5}
                    ]
            )
        else:
            return V0038Licenses(
        )
        """

    def testV0038Licenses(self):
        """Test V0038Licenses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
